### ISSUE TITLE
Trending music in my location?

### ISSUE THREAD

**Issue by blogdemoi** [NimaKhajehpour/DemoMusix#1]
Hello,

Thank you for this app.
In the description it is said music can be chosen depending on my location. However I don't see any settings in the app about that...

**Comment by NimaKhajehpour** [comment]
Hello and thanks for the feedback on the application. Maybe the wording is wrong a little. At launch the app sends the request to deezar api and according to the ip address the request was sent with, aka your location, the data is received. So it is depending on your ip address. Sorry for the wrong info on description. I appreciate the feedback and i will change the description in future updates.

**Comment by blogdemoi** [comment]
OK, I understand now.

**Comment by NimaKhajehpour** [comment]
Yeah sorry for the misinformation, thanks for downloading the app :heart:  I will change the description in the next update so that its more clear.
